name: Auto Sync
on:
  schedule:
    - cron: '0 8 * * 5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: vesoft-inc/auto-sync-repos@master
      with:
        from_repo: coolsnowwolf/lede
        repo_token: ${{ secrets.GITHUB_TOKEN }}
